// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmsmnfjcmzqqmzdejztx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxtc21uZmpjbXpxcW16ZGVqenR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzAxNzYsImV4cCI6MjA3MTU0NjE3Nn0.C9WteJnLCu30ga-Bw0vUDj-Mp6zrg7TI9smxNwDSarg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});